models/Menu.php
<?php

namespace app\models;

use Yii;
use \app\models\base\Menu as BaseMenu;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "menu".
 */
class Menu extends BaseMenu
{
    
}

controllers/MenuController.php
<?php

namespace app\controllers;

use app\models\Menu;
use yii\web\HttpException;

/**
 * MenuController implements the CRUD actions for Menu model.
 */
class MenuController extends BaseController
{
    public function actionIndex()
    {
        $model = new Menu();

        return $this->render('index', ['model' => $model]);
    }

    public function actionLoadContent()
    {
        return $this->renderPartial('index-output');
    }

    public function actionCreate()
    {
        $model = new Menu();

        if ($model->load($_POST)) {
            $model->icon = "fa " . $model->icon;
            if ($model->save()) {
                \Yii::$app->getSession()->setFlash('success', "Menu baru berhasil ditambah");
            } else {
                \Yii::$app->getSession()->setFlash('error', "Menu baru gagal ditambah");
            }
        }

        return $this->redirect(['index']);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model) {
            $model->name = $_POST['name'];
            $model->controller = $_POST['controller'];
            $model->icon = $_POST['icon'];
            $model->parent_id = $_POST['parent_id'];
            $model->menu_kategori_id = $_POST['menu_kategori_id'];
            $model->save(false);
        }
    }

    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model) {
            $model->is_deleted = 1;
            $model->save();
            return $this->renderPartial('index-output');
        }
    }

    public function actionSaveOrder()
    {
        $str = $_POST['str'];
        $trs = explode("||", $str);
        $no = 1;
        foreach ($trs as $tr) {
            $obj = explode("[=]", $tr);
            /** @var Menu $menu */
            $menu = $this->findModel($obj[0]);
            $menu->name = $obj[1];
            $menu->controller = $obj[2];
            $menu->parent_id = $obj[3];
            $menu->order = $no;
            $menu->icon = $obj[4];
            $menu->menu_kategori_id = $obj[5];
            $menu->save();
            $no++;
        }
    }

    /**
     * Finds the Menu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Menu the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Menu::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

controllers/RoleController.php
<?php

namespace app\controllers;

use app\components\Tabs;
use app\models\Role;
use app\models\RoleMenu;
use app\models\search\RoleSearch;
use yii\helpers\Url;
use yii\web\HttpException;

/**
 * RoleController implements the CRUD actions for Role model.
 */
class RoleController extends BaseController
{
    /**
     * @var boolean whether to enable CSRF validation for the actions in this controller.
     * CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
     */
    public $enableCsrfValidation = false;

    /**
     * Lists all Role models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new RoleSearch();
        $dataProvider = $searchModel->search($_GET);

        Tabs::clearLocalStorage();

        Url::remember();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * Displays a single Role model.
     * @param integer $id
     *
     * @return mixed
     */
    public function actionView($id)
    {
        Url::remember();
        Tabs::rememberActiveState();

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Role model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Role;

        try {
            if ($model->load($_POST) && $model->save()) {
                return $this->redirect(Url::previous());
            } elseif (!\Yii::$app->request->isPost) {
                $model->load($_GET);
            }
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            $model->addError('_exception', $msg);
        }
        return $this->render('create', ['model' => $model]);
    }

    /**
     * Updates an existing Role model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load($_POST) && $model->save()) {
            return $this->redirect(Url::previous());
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Role model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $this->findModel($id)->delete();
        } catch (\Exception $e) {
            $msg = (isset($e->errorInfo[2])) ? $e->errorInfo[2] : $e->getMessage();
            \Yii::$app->getSession()->setFlash('error', $msg);
            return $this->redirect(Url::previous());
        }

        // TODO: improve detection
        $isPivot = strstr('$id', ',');
        if ($isPivot == true) {
            return $this->redirect(Url::previous());
        } elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
            Url::remember(null);
            $url = \Yii::$app->session['__crudReturnUrl'];

            return $this->redirect($url);
        } else {
            return $this->redirect(['index']);
        }
    }

    public function actionDetail($id)
    {
        $model = $this->findModel($id);

        if (isset($_POST['menu'])) {
            RoleMenu::deleteAll(["role_id" => $id]);
            $menus = $_POST['menu'];
            foreach ($menus as $menu) {
                $roleMenu = new RoleMenu();
                $roleMenu->role_id = $id;
                $roleMenu->menu_id = $menu;
                $roleMenu->save();
            }
            \Yii::$app->session->addFlash("success", "Role " . $model->name . " successfully updated.");
            return $this->redirect(["index"]);
        }

        return $this->render('detail', [
            'model' => $model,
        ]);
    }

    /**
     * Finds the Role model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Role the loaded model
     * @throws HttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Role::findOne($id)) !== null) {
            return $model;
        } else {
            throw new HttpException(404, 'The requested page does not exist.');
        }
    }
}

views/menu/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \app\components\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Menu $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin(
    [
        'id' => 'Menu',
        'layout' => 'horizontal',
        'enableClientValidation' => true,
        'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
);
?>
<div class="card-body">
    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'controller')->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'icon')->textInput(['class' => "form-control icp-auto"]) ?>
    <?php echo $form->errorSummary($model); ?>
</div>
<div class="card-footer">
    <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-info primary-btn']); ?>
    <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
</div>
<?php ActiveForm::end(); ?>

<?php
$this->registerJs('$(".icp-auto").iconpicker();');
?>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $(".form-group").addClass('row');

        function functionMaxwidth(x) {
            if (x.matches) {
                $(".control-label").attr("style", "text-align:right");
            }
        }

        var x = window.matchMedia("(min-width: 576px)")
        functionMaxwidth(x)
        x.addListener(functionMaxwidth)
    });
</script>

views/menu/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var common\models\search\MenuSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="menu-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

	<?= $form->field($model, 'id') ?>

	<?= $form->field($model, 'name') ?>

	<?= $form->field($model, 'controller') ?>

	<?= $form->field($model, 'action') ?>

	<?= $form->field($model, 'icon') ?>

	<?php // echo $form->field($model, 'order') 
	?>

	<?php // echo $form->field($model, 'parent_id') 
	?>

	<div class="form-group">
		<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
		<?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>

views/menu/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var common\models\Menu $model
 */

$this->title = 'Tambah';
$this->params['breadcrumbs'][] = ['label' => 'Menu', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="card card-info primary-card card-outline">
    <div class="card-header">
        <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
    </div>
    <?php echo $this->render('_form', [
        'model' => $model,
    ]); ?>
</div>

views/menu/index-output.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

$parents = \yii\helpers\ArrayHelper::map(\app\models\Menu::find()->where(["parent_id" => null])->andWhere(["is_deleted" => 0])->orderBy("`order` ASC")->all(), "id", "name");
$kategoriMenu = \yii\helpers\ArrayHelper::map(\app\models\MenuKategori::find()->all(), "id", "nama");

?>

<?php foreach (\app\models\Menu::find()->where(["parent_id" => null])->andWhere(["is_deleted" => 0])->orderBy("`order` ASC")->all() as $menu) { ?>
    <tr data="<?= $menu->id ?>">
        <td style="padding: 10px 40px 0 10px; border-radius:10px; display: flex; flex-direction:row;">
            <div style="flex:1; padding:10px 20px; border-radius:6px; border:1px solid #bbb; margin-bottom:15px;">
                <div style="display: flex; flex-direction:row; cursor: pointer;" class="downdrop" data-id="<?= $menu->id ?>">
                    <div style="flex:1;">
                        <div style="font-weight:normal; margin-bottom:0;">&nbsp;&nbsp;<?= $menu->name; ?></div>
                    </div>
                    <div class="downdrop-icon">
                        <i class="fa fa-angle-left"></i>
                    </div>
                </div>
                <div class="downdrop-item" style="padding: 10px 0;">
                    <div style="border-top:1px solid #ccc; padding: 20px 20px 0 20px;">
                        <div class="form-group">
                            <label>Nama Menu</label>
                            <?= Html::textInput("name", $menu->name, ["class" => "form-control name", "id" => "name-" . $menu->id]) ?>
                        </div>
                        <div class="form-group">
                            <label>Controller</label>
                            <?= Html::textInput("controller", $menu->controller, ["class" => "form-control controller", "id" => "controller-" . $menu->id]) ?>
                        </div>
                        <div class="form-group">
                            <label>Ikon</label>
                            <?= Html::textInput("icon", $menu->icon, ["class" => "form-control icon", "id" => "icp-auto-" . $menu->id, "role" => "iconpicker"]) ?>
                        </div>
                        <div class="form-group">
                            <label>Induk</label>
                            <?= Html::dropDownList("parent_id", $menu->parent_id, $parents, ["class" => "form-control parent_id", "id" => "parent_id-" . $menu->id, "prompt" => "-"]) ?>
                        </div>
                        <div class="form-group">
                            <label>Kategori Menu</label>
                            <?= Html::dropDownList("menu_kategori_id", $menu->menu_kategori_id, $kategoriMenu, ["class" => "form-control menu_kategori_id", "id" => "menu_kategori_id-" . $menu->id, "prompt" => "-"]) ?>
                        </div>
                        <div style="margin-top: 30px; display: flex; flex-direction:row; align-items:center;">
                            <a href="#" class="text-danger btnHapusMenuAjax" style="flex: 1;" data-id="<?= $menu->id ?>">Hapus Menu</a>
                            <button class="btn primary-btn elevation-1 btnSimpanMenuAjax" style="padding:10px 30px;" data-id="<?= $menu->id ?>">SIMPAN</button>
                        </div>
                    </div>
                </div>
            </div>
            <div style="padding-left: 10px;">
                <div class="sorterer" style="padding:10px 15px; border-radius:8px;">
                    <i class='fas fa-arrows-alt'></i>
                </div>
            </div>
        </td>
    </tr>
    <?php foreach (\app\models\Menu::find()->where(["parent_id" => $menu->id])->andWhere(["is_deleted" => 0])->orderBy("`order` ASC")->all() as $menu2) { ?>
        <tr data="<?= $menu2->id ?>">
            <td style="padding: 10px 10px 0 40px; display: flex; flex-direction:row;">
                <div style="flex:1; padding:10px 20px; border-radius:6px; border:1px solid #bbb; margin-bottom:15px;">
                    <div style="display: flex; flex-direction:row; cursor: pointer;" class="downdrop" data-id="<?= $menu2->id ?>">
                        <div style="flex:1;">
                            <div style="font-weight:normal; margin-bottom:0;">&nbsp;&nbsp;<?= $menu2->name; ?></div>
                        </div>
                        <div class="downdrop-icon">
                            <i class="fa fa-angle-left"></i>
                        </div>
                    </div>
                    <div class="downdrop-item" style="padding: 10px 0;">
                        <div style="border-top:1px solid #ccc; padding: 20px 20px 0 20px;">
                            <div class="form-group">
                                <label>Nama Menu</label>
                                <?= Html::textInput("name", $menu2->name, ["class" => "form-control name", "id" => "name-" . $menu2->id]) ?>
                            </div>
                            <div class="form-group">
                                <label>Controller</label>
                                <?= Html::textInput("controller", $menu2->controller, ["class" => "form-control controller", "id" => "controller-" . $menu2->id]) ?>
                            </div>
                            <div class="form-group">
                                <label>Ikon</label>
                                <?= Html::textInput("icon", $menu2->icon, ["class" => "form-control icon", "id" => "icp-auto-" . $menu2->id]) ?>
                            </div>
                            <div class="form-group">
                                <label>Induk</label>
                                <?= Html::dropDownList("parent_id", $menu2->parent_id, $parents, ["class" => "form-control parent_id", "id" => "parent_id-" . $menu2->id, "prompt" => "-"]) ?>
                            </div>
                            <div class="form-group">
                                <label>Kategori Menu</label>
                                <?= Html::dropDownList("menu_kategori_id", $menu2->menu_kategori_id, $kategoriMenu, ["class" => "form-control menu_kategori_id", "id" => "menu_kategori_id-" . $menu2->id, "prompt" => "-"]) ?>
                            </div>
                            <div style="margin-top: 30px; display: flex; flex-direction:row; align-items:center;">
                                <a href="#" class="text-danger btnHapusMenuAjax" style="flex: 1;" data-id="<?= $menu2->id ?>">Hapus Menu</a>
                                <button class="btn primary-btn elevation-1 btnSimpanMenuAjax" style="padding:10px 30px;" data-id="<?= $menu2->id ?>">SIMPAN</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div style="padding-left: 10px;">
                    <div class="sorterer" style="padding:10px 15px; border-radius:8px;">
                        <i class='fas fa-arrows-alt'></i>
                    </div>
                </div>
            </td>
        </tr>
    <?php } ?>
<?php } ?>

<script>
    $(".downdrop").click(function() {
        var id = $(this).attr('data-id');
        $("#icp-auto-" + id).iconpicker();
        this.parentElement.querySelector(".downdrop-item").classList.toggle("downdrop-item-active");
        this.parentElement.querySelector(".downdrop-icon").classList.toggle("downdrop-icon-down");
    });

    $(".btnHapusMenuAjax").click(function(e) {
        if (confirm("Apakah anda yakin? data akan dihapus sistem secara permanen") == true) {
            var id = $(this).attr('data-id');
            $('#konten-menu').load("<?= Url::to(['delete']) ?>" + "?id=" + id);
        }
    });

    $(".btnSimpanMenuAjax").click(function(e) {
        var id = $(this).attr('data-id');
        $.ajax({
            url: "<?= Url::to(["update"])  ?>" + "?id=" + id,
            data: {
                name: $("#name-" + id).val(),
                controller: $("#controller-" + id).val(),
                icon: $("#icp-auto-" + id).val(),
                parent_id: $("#parent_id-" + id).val(),
                menu_kategori_id: $("#menu_kategori_id-" + id).val(),
            },
            type: "post",
            success: function() {
                alert("Menu berhasil disimpan");
                loadKonten();
            }
        });
        return false;
    });
</script>

views/menu/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var common\models\Menu $model
 */

$this->title = 'Update Menu - ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Menu', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Edit';
?>
<div class="card card-info primary-card card-outline">
    <div class="card-header">
        <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
    </div>
    <?php echo $this->render('_form', [
        'model' => $model,
    ]); ?>
</div>

views/menu/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\Tabs;

/**
 * @var yii\web\View $this
 * @var common\models\Menu $model
 */

$this->title = 'Menu ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud menu-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'List Menus', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>
                <?= $model->name ?> </h2>
        </div>

        <div class="panel-body">



            <?php $this->beginBlock('common\models\Menu'); ?>

            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'name',
                    'controller',
                    'action',
                    'icon',
                    'order',
                    // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'parent_id',
                        'value' => ($model->getParent()->one() ? Html::a($model->getParent()->one()->name, ['menu/view', 'id' => $model->getParent()->one()->id,]) : '<span class="label label-warning">?</span>'),
                    ],
                ],
            ]); ?>

            <hr />

            <?= Html::a(
                '<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
                ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]
            ); ?>
            <?php $this->endBlock(); ?>



            <?php $this->beginBlock('Menuses'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Menuses',
                        ['menu/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Menus',
                        ['menu/create', 'Menus' => ['parent_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div><?php Pjax::begin(['id' => 'pjax-Menuses', 'enableReplaceState' => false, 'linkSelector' => '#pjax-Menuses ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getMenus(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-menuses']]),
                'pager'        => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel'  => 'Last'
                ],
                'columns' => [
                    [
                        'class'      => 'yii\grid\ActionColumn',
                        'template'   => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            // using the column name as key, not mapping to 'id' like the standard generator
                            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                            $params[0] = 'menu' . '/' . $action;
                            return $params;
                        },
                        'buttons'    => [],
                        'controller' => 'menu'
                    ],
                    'id',
                    'name',
                    'controller',
                    'action',
                    'icon',
                    'order',
                ]
            ]) . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?php $this->beginBlock('RoleMenuses'); ?>
            <div style='position: relative'>
                <div style='position:absolute; right: 0px; top 0px;'>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Role Menuses',
                        ['role-menu/index'],
                        ['class' => 'btn text-muted btn-xs']
                    ) ?>
                    <?= Html::a(
                        '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Role Menus',
                        ['role-menu/create', 'RoleMenus' => ['menu_id' => $model->id]],
                        ['class' => 'btn btn-success btn-xs']
                    ); ?>
                </div>
            </div><?php Pjax::begin(['id' => 'pjax-RoleMenuses', 'enableReplaceState' => false, 'linkSelector' => '#pjax-RoleMenuses ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>
            <?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRoleMenus(), 'pagination' => ['pageSize' => 20, 'pageParam' => 'page-rolemenuses']]),
                'pager'        => [
                    'class'          => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel'  => 'Last'
                ],
                'columns' => [
                    [
                        'class'      => 'yii\grid\ActionColumn',
                        'template'   => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            // using the column name as key, not mapping to 'id' like the standard generator
                            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                            $params[0] = 'role-menu' . '/' . $action;
                            return $params;
                        },
                        'buttons'    => [],
                        'controller' => 'role-menu'
                    ],
                    'id',
                    // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'role_id',
                        'value' => function ($model) {
                            if ($rel = $model->getRole()->one()) {
                                return Html::a($rel->name, ['role/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                ]
            ]) . '</div>' ?>
            <?php Pjax::end() ?>
            <?php $this->endBlock() ?>


            <?= Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label'   => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['common\models\Menu'],
                        'active'  => true,
                    ], [
                        'content' => $this->blocks['Menuses'],
                        'label'   => '<small>Menuses <span class="badge badge-default">' . count($model->getMenus()->asArray()->all()) . '</span></small>',
                        'active'  => false,
                    ], [
                        'content' => $this->blocks['RoleMenuses'],
                        'label'   => '<small>Role Menuses <span class="badge badge-default">' . count($model->getRoleMenus()->asArray()->all()) . '</span></small>',
                        'active'  => false,
                    ],]
                ]
            );
            ?>
        </div>
    </div>
</div>